version: '3.3'

services:

  back-end:
    user: "root"
    build:
      context: ./src
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput  && python manage.py makemigrations && python manage.py migrate &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000 --access-logfile -"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - "80:8000"
    env_file:
      - ./src/.env/


  db:
    image: postgres:15.1-alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - ./src/.env/

volumes:
  postgres_data:
  static_volume:
  media_volume: