# Generated by Django 5.0.7 on 2024-07-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='url',
            field=models.URLField(default='https://google.com', verbose_name='Ссылка на вакансию'),
            preserve_default=False,
        ),
    ]
