# Generated by Django 5.0.7 on 2024-08-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_founder_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founder',
            name='url',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='url',
            field=models.URLField(default='https://lolcal.com', verbose_name='Ссылка на вакансию'),
            preserve_default=False,
        ),
    ]
