# Generated by Django 5.0.7 on 2024-08-08 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('avatar', models.ImageField(upload_to='avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'svg'], message='this avatar extension is not allowed...')], verbose_name='Аватар клиента')),
                ('fullname', models.CharField(max_length=120, verbose_name='Полное имя')),
                ('position', models.CharField(max_length=120, verbose_name='Должность')),
                ('company_name', models.CharField(max_length=120, verbose_name='Наименование компании')),
                ('star', models.PositiveIntegerField(verbose_name='Звезд')),
                ('description', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
