# Generated by Django 5.0.7 on 2024-07-20 12:45

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.PositiveIntegerField(verbose_name='Звезд: '),
        ),
    ]
