# Generated by Django 5.0.7 on 2024-07-22 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='avatar',
            field=models.ImageField(upload_to='avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'svg'], message='this avatar extension is not allowed...')], verbose_name='Аватар клиента'),
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.PositiveIntegerField(verbose_name='Звезд'),
        ),
    ]
