# Generated by Django 5.0.7 on 2024-07-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('img', models.ImageField(upload_to='portfolio/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('description', models.TextField(verbose_name='Описание процесса')),
            ],
            options={
                'verbose_name': 'Процесс',
                'verbose_name_plural': 'Процессы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('position', models.CharField(max_length=120, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('portfolios', models.ManyToManyField(related_name='tab_portfolios', to='service.portfolio', verbose_name='Портфолио')),
                ('processes', models.ManyToManyField(related_name='tab_processes', to='service.process', verbose_name='Процессы')),
                ('sections', models.ManyToManyField(related_name='tab_sections', to='service.section', verbose_name='Секции')),
                ('team', models.ManyToManyField(related_name='tab_team', to='service.teammember', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Таб',
                'verbose_name_plural': 'Табы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('tabs', models.ManyToManyField(related_name='service_tabs', to='service.tab', verbose_name='Табы')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
