# Generated by Django 5.0.7 on 2024-08-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description_for_banner',
            field=models.CharField(default=1, help_text='Макс. символов: 90', max_length=90, verbose_name='Краткое описание для баннера главной страницы'),
            preserve_default=False,
        ),
    ]
