# Generated by Django 5.0.7 on 2024-08-06 17:32

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_short_description_for_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gif',
            field=models.FileField(blank=True, help_text='Загрузите гифку для услуги. Допустимые форматы: .gif', null=True, upload_to='gifs/', validators=[service.models.validate_gif], verbose_name='Гифка'),
        ),
    ]
