# Generated by Django 5.0.7 on 2024-08-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='tabs',
            field=models.ManyToManyField(blank=True, null=True, related_name='service_tabs', to='service.tab', verbose_name='Табы'),
        ),
    ]
