# Generated by Django 5.0.7 on 2024-08-06 17:38

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_tabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='gif',
            field=models.FileField(default=1, help_text='Загрузите гифку для услуги. Допустимые форматы: .gif', upload_to='gifs/', validators=[service.models.validate_gif], verbose_name='Гифка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='tabs',
            field=models.ManyToManyField(related_name='service_tabs', to='service.tab', verbose_name='Табы'),
        ),
    ]
