# Generated by Django 5.0.7 on 2024-08-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('number_or_email', models.CharField(max_length=30, verbose_name='Имя или email')),
                ('review', models.TextField(verbose_name='Комментарий или запрос клиента')),
                ('service', models.ManyToManyField(related_name='form_service', to='service.service', verbose_name='Какая услуга(-и) интересует клиента')),
            ],
            options={
                'verbose_name': 'Данные с формы',
                'verbose_name_plural': 'Данные с формы',
            },
        ),
    ]
