# Generated by Django 5.0.7 on 2024-08-08 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('price', models.CharField(max_length=120, verbose_name='Сделанная прибыль')),
                ('image', models.ImageField(upload_to='images/portfolio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('link', models.URLField(help_text='Ссылка на проект или ресурс.', verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
