# Generated by Django 5.0.7 on 2024-07-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='price',
            field=models.CharField(max_length=120, verbose_name='Сделанная прибыль'),
        ),
    ]
