# Generated by Django 5.0.7 on 2024-08-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.URLField(default=1, help_text='Ссылка на проект или ресурс.', verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
